name: "[CI] Test"

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.0.6
  CI: "true"

jobs:
  test-report:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 119.0.6045.105

      - name: List Chrome
        shell: "bash"
        run: apt list --installed | grep chrome

      - name: Remove Chrome
        shell: "bash"
        run: sudo apt remove google-chrome-stable

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 119.0.6045.105

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Setup Database
        run: bundle exec rake test_app
    
      - name: Run RSpec
        run: bundle exec rspec
        env:
          SIMPLECOV: "true"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: openpoke/decidim-module-anonymous_codes

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
